"""Tests for robustqr.

Fixtures are generated by tests/make_fixtures.py (committed PNGs, so the
suite runs without the qrcode package). pyzbar-dependent tests skip
gracefully when libzbar is absent.
"""

from pathlib import Path

import pytest

from robustqr import decode, decode_all
from robustqr.engines import OpenCVEngine, PyzbarEngine, WeChatEngine, available_engines
from robustqr.pipeline import engine_report

FIX = Path(__file__).parent / "fixtures"
PAYLOAD = "https://example.com/robustqr-test"

wechat_available = WeChatEngine().available
pyzbar_available = PyzbarEngine().available


def test_engine_report_lists_all_engines():
    report = engine_report()
    assert "wechat" in report and "opencv" in report and "pyzbar" in report


def test_clean_decodes():
    r = decode(FIX / "clean.png")
    assert r is not None and r.data == PAYLOAD
    assert r.engine and r.variant  # provenance is stamped


def test_small_decodes():
    assert decode(FIX / "small.png").data == PAYLOAD


def test_rotated_decodes():
    assert decode(FIX / "rotated.png").data == PAYLOAD


def test_lowcontrast_decodes():
    assert decode(FIX / "lowcontrast.png").data == PAYLOAD


def test_perspective_decodes():
    assert decode(FIX / "perspective.png").data == PAYLOAD


@pytest.mark.skipif(not wechat_available, reason="opencv-contrib not installed")
def test_wrinkled_decodes_via_pipeline():
    """The hoodie case: full pipeline cracks the wrinkled fixture."""
    r = decode(FIX / "wrinkled.png")
    assert r is not None and r.data == PAYLOAD


@pytest.mark.skipif(not wechat_available, reason="opencv-contrib not installed")
def test_wrinkled_defeats_classical_engines():
    """The wrinkle fixture is meaningful: classical engines fail it.

    This mirrors the real incident — pyzbar and plain OpenCV could not
    read the wrinkled hoodie; only the DNN engine could.
    """
    assert decode(FIX / "wrinkled.png", engines=[OpenCVEngine()]) is None


@pytest.mark.skipif(not wechat_available, reason="opencv-contrib not installed")
def test_pipeline_prefers_strongest_engine():
    """decode_all returns hits in attempt order; wechat is tried first."""
    hits = decode_all(FIX / "wrinkled.png")
    assert hits and hits[0].engine == "wechat"


def test_no_qr_returns_none():
    import numpy as np

    blank = np.full((200, 200, 3), 255, dtype=np.uint8)
    assert decode(blank) is None


def test_missing_file_raises():
    with pytest.raises(FileNotFoundError):
        decode(FIX / "does-not-exist.png")


def test_unavailable_engine_is_reported_not_fatal():
    engines = available_engines()
    assert all(e.available for e in engines)
    if not pyzbar_available:
        assert "pyzbar" in engine_report()  # listed, marked unavailable


@pytest.mark.skipif(not pyzbar_available, reason="libzbar not installed")
def test_pyzbar_engine_decodes_clean():
    r = decode(FIX / "clean.png", engines=[PyzbarEngine()], variants=["original"])
    assert r is not None and r.data == PAYLOAD
